name: 'Build and push a docker image'
description: 'Set up docker buildx, build and push image to ECR'
inputs:
  ECR_REGISTRY:
    description: 'AWS ECR Registry url'
    required: true
  ECR_REPOSITORY:
    description: 'Repository name where to push the image to'
    required: true
  GH_SHA:
    description: 'Hash of commit or semantic versioning to use as image tag'
    required: true
  NPM_TOKEN:
    description: 'GitHub token to download private libraries'
    required: true
outputs:
  IMAGE_NAME:
    description: "A FQDN of the image to be built and pushed"
    value: ${{ steps.image.outputs.NAME }}
  IMAGE_TAG:
    description: "Only the tag of the image"
    value: ${{ steps.image.outputs.TAG }}
runs:
  using: "composite"
  steps:
    - name: Export image variables
      id: image
      run: |
        echo "NAME=${{ inputs.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.GH_SHA }}" >> $GITHUB_OUTPUT
        echo "TAG=${{ inputs.GH_SHA }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker build & push
      uses: docker/build-push-action@v3
      id: docker-build
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.image.outputs.NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          NPM_TOKEN=${{ inputs.NPM_TOKEN }}
          COMMIT=${{ github.sha }}
